INSERT INTO art_print (Technique_id, Picture_title) VALUES
(05,'Space print n.1'),
(09,'Space print n.1'),
(05,'Space print n.2'),
(09,'Space print n.2'),
(05,'Space print n.3'),
(09,'Space print n.3'),
(05,'Film print n.1'),
(05,'Film print n.2'),
(05,'Film print n.3'),
(05,'Film print n.4'),
(05,'Film print n.5'),
(09,'Film print n.1'),
(09,'Film print n.2'),
(09,'Film print n.3'),
(09,'Film print n.4'),
(09,'Film print n.5'),
(05,'Street print n.1'),
(05,'Street print n.2'),
(05,'Street print n.3'),
(05,'Street print n.4'),
(09,'Street print n.1'),
(09,'Street print n.2'),
(09,'Street print n.3'),
(09,'Street print n.4'),
(05,'Nature print n.1'),
(05,'Nature print n.2'),
(05,'Nature print n.3'),
(05,'Nature print n.4'),
(05,'Nature print n.5'),
(05,'Nature print n.6'),
(05,'Nature print n.7'),
(09,'Nature print n.1'),
(09,'Nature print n.2'),
(09,'Nature print n.3'),
(09,'Nature print n.4'),
(09,'Nature print n.5'),
(09,'Nature print n.6'),
(09,'Nature print n.7'),
(01,'Abstract print n.1'),
(02,'Abstract print n.1'),
(03,'Abstract print n.1'),
(04,'Abstract print n.1'),
(05,'Abstract print n.1'),
(06,'Abstract print n.2'),
(02,'Abstract print n.2'),
(03,'Abstract print n.2'),
(04,'Abstract print n.2'),
(05,'Abstract print n.2'),
(06,'Abstract print n.3'),
(07,'Abstract print n.3'),
(03,'Abstract print n.3'),
(04,'Abstract print n.3'),
(05,'Abstract print n.3'),
(06,'Abstract print n.4'),
(07,'Abstract print n.4'),
(08,'Abstract print n.4'),
(04,'Abstract print n.4'),
(05,'Abstract print n.4'),
(06,'Abstract print n.5'),
(07,'Abstract print n.5'),
(08,'Abstract print n.5'),
(09,'Abstract print n.5'),
(05,'Abstract print n.5'),
(06,'Abstract print n.6'),
(07,'Abstract print n.6'),
(08,'Abstract print n.6'),
(09,'Abstract print n.6'),
(05,'Abstract print n.6'),
(01,'Black and white building'),
(02,'Black and white building'),
(03,'Black and white building'),
(04,'Black and white building'),
(05,'Black and white building'),
(03,'Modern spiral building'),
(04,'Modern spiral building'),
(05,'Modern spiral building'),
(06,'Modern spiral building'),
(07,'Modern spiral building'),
(05,'Skyscraper on fog'),
(06,'Skyscraper on fog'),
(07,'Skyscraper on fog'),
(08,'Skyscraper on fog'),
(09,'Skyscraper on fog'),
(02,'White building'),
(03,'White building'),
(04,'White building'),
(05,'White building'),
(06,'White building'),

(01,'Golconda'),
(02,'Golconda'),
(03,'Golconda'),
(04,'Golconda'),
(05,'Golconda'),
(06,'Golconda'),
(07,'Golconda'),
(08,'Golconda'),
(09,'Golconda'),

(01,'Portrait of Joseph Roulin'),
(02,'Portrait of Joseph Roulin'),
(03,'Portrait of Joseph Roulin'),
(04,'Portrait of Joseph Roulin'),
(05,'Portrait of Joseph Roulin'),
(06,'Portrait of Joseph Roulin'),
(07,'Portrait of Joseph Roulin'),
(08,'Portrait of Joseph Roulin'),
(09,'Portrait of Joseph Roulin'),

(01,'The persistence of memory'),
(02,'The persistence of memory'),
(03,'The persistence of memory'),
(04,'The persistence of memory'),
(05,'The persistence of memory'),
(06,'The persistence of memory'),
(07,'The persistence of memory'),
(08,'The persistence of memory'),
(09,'The persistence of memory'),

(01,'Impression, Sunrise'),
(02,'Impression, Sunrise'),
(03,'Impression, Sunrise'),
(04,'Impression, Sunrise'),
(05,'Impression, Sunrise'),
(06,'Impression, Sunrise'),
(07,'Impression, Sunrise'),
(08,'Impression, Sunrise'),
(09,'Impression, Sunrise'),

(01,'The Cardsharps'),
(02,'The Cardsharps'),
(03,'The Cardsharps'),
(04,'The Cardsharps'),
(05,'The Cardsharps'),
(06,'The Cardsharps'),
(07,'The Cardsharps'),
(08,'The Cardsharps'),
(09,'The Cardsharps'),

(01,'Lady with an Ermine'),
(02,'Lady with an Ermine'),
(03,'Lady with an Ermine'),
(04,'Lady with an Ermine'),
(05,'Lady with an Ermine'),
(06,'Lady with an Ermine'),
(07,'Lady with an Ermine'),
(08,'Lady with an Ermine'),
(09,'Lady with an Ermine'),

(01,'Girl with a pearl earring'),
(02,'Girl with a pearl earring'),
(03,'Girl with a pearl earring'),
(04,'Girl with a pearl earring'),
(05,'Girl with a pearl earring'),
(06,'Girl with a pearl earring'),
(07,'Girl with a pearl earring'),
(08,'Girl with a pearl earring'),
(09,'Girl with a pearl earring'),

(01,'Portrait of Lucina Brembati'),
(02,'Portrait of Lucina Brembati'),
(03,'Portrait of Lucina Brembati'),
(04,'Portrait of Lucina Brembati'),
(05,'Portrait of Lucina Brembati'),
(06,'Portrait of Lucina Brembati'),
(07,'Portrait of Lucina Brembati'),
(08,'Portrait of Lucina Brembati'),
(09,'Portrait of Lucina Brembati'),

(01,'After Lunch (The Trellis)'),
(02,'After Lunch (The Trellis)'),
(03,'After Lunch (The Trellis)'),
(04,'After Lunch (The Trellis)'),
(05,'After Lunch (The Trellis)'),
(06,'After Lunch (The Trellis)'),
(07,'After Lunch (The Trellis)'),
(08,'After Lunch (The Trellis)'),
(09,'After Lunch (The Trellis)');